apiVersion: apps/v1
kind: Deployment
metadata:
  name: dst-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dst-server
  template:
    metadata:
      labels:
        app: dst-server
        karpenter.sh/capacity-type: spot
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: karpenter.sh/capacity-type
                operator: In
                values:
                - spot
      containers:
      - name: dst-server
        image: dst-server-with-monitor:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 11000
          protocol: UDP
        - containerPort: 11003
          protocol: UDP
        - containerPort: 8080
          protocol: TCP
        env:
        - name: STEAMAPPID
          value: "343050"
        - name: STEAMAPP
          value: "dst"
        - name: STEAMAPPDIR
          value: "/home/steam/dst-dedicated"
        - name: CLUSTER_TOKEN
          valueFrom:
            secretKeyRef:
              name: dst-secrets
              key: cluster-token
        resources:
          requests:
            cpu: "500m"
            memory: "1Gi"
          limits:
            cpu: "2"
            memory: "4Gi"
        readinessProbe:
          exec:
            command:
            - pgrep
            - -f
            - dontstarve_dedicated_server_nullrenderer
          initialDelaySeconds: 40
          periodSeconds: 30
        livenessProbe:
          exec:
            command:
            - pgrep
            - -f
            - dontstarve_dedicated_server_nullrenderer
          initialDelaySeconds: 40
          periodSeconds: 30
        volumeMounts:
        - name: mods-config
          mountPath: /home/steam/dst-dedicated/mods
        - name: dst-data
          mountPath: /home/steam/.klei/DoNotStarveTogether
      volumes:
      - name: mods-config
        configMap:
          name: dst-mods-config
      - name: dst-data
        persistentVolumeClaim:
          claimName: dst-data-pvc