apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: dst-server-provisioner
spec:
  requirements:
    - key: karpenter.sh/capacity-type
      operator: In
      values: ["spot"]
    - key: kubernetes.io/arch
      operator: In
      values: ["amd64"]
    - key: node.kubernetes.io/instance-type
      operator: In
      values: ["c5.large", "c5a.large"]
  limits:
    resources:
      cpu: 4
      memory: 8Gi
  providerRef:
    name: default
  ttlSecondsAfterEmpty: 30
  ttlSecondsUntilExpired: 2592000 # 30 days
  consolidation:
    enabled: true
---
apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: default
spec:
  subnetSelector:
    karpenter.sh/discovery: dst-server
  securityGroupSelector:
    karpenter.sh/discovery: dst-server
  tags:
    KarpenerProvisionerName: "dst-server-provisioner"
    Project: "dst-server"
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeSize: 20Gi
        volumeType: gp3
        encrypted: true