apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dst-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi
  storageClassName: gp3  # This is for AWS EKS. Adjust if using a different cloud provider.