apiVersion: v1
kind: Service
metadata:
  name: dst-server-service
spec:
  selector:
    app: dst-server
  ports:
    - name: game-udp-1
      port: 11000
      targetPort: 11000
      protocol: UDP
    - name: game-udp-2
      port: 11003
      targetPort: 11003
      protocol: UDP
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
  type: LoadBalancer