name: Deploy DST Server

on:
  push:
    branches:
      - main

permissions:
  id-token: write  # Required for GitHub OIDC
  contents: read   # Required for actions/checkout

jobs:
  deploy-dst-server:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build and push DST Server Docker image to ECR
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ steps.login-ecr.outputs.registry }}/dst-server:latest
            ${{ steps.login-ecr.outputs.registry }}/dst-server:${{ github.sha }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      - name: Deploy DST Server to App Runner
        uses: awslabs/amazon-app-runner-deploy@main
        env:
          STEAMAPPID: 343050
          STEAMAPP: dst
          STEAMAPPDIR: /home/steam/dst-dedicated
          CLUSTER_TOKEN: ${{ secrets.CLUSTER_TOKEN }}
        with:
          service: DSTServer
          image: ${{ steps.login-ecr.outputs.registry }}/dst-server:latest
          port: 8080
          access-role-arn: ${{ secrets.AWS_ROLE_ARN }}
          region: ${{ secrets.AWS_REGION }}
          cpu: 2
          memory: 4
          copy-env-vars: |
            STEAMAPPID
            STEAMAPP
            STEAMAPPDIR
            CLUSTER_TOKEN
          instance-role-arn: ${{ secrets.INSTANCE_ROLE_ARN }}