name: Deploy DST Server

on:
  push:
    branches:
      - main

permissions:
  id-token: write  # Required for GitHub OIDC
  contents: read   # Required for actions/checkout

jobs:
  check-deploy-caves:
    runs-on: ubuntu-latest
    outputs:
      should_deploy: ${{ steps.check_secret.outputs.deploy_caves }}
    steps:
      - name: Check DEPLOY_CAVES secret
        id: check_secret
        run: |
          # Check if the DEPLOY_CAVES secret is set to true
          if [ "${{ secrets.DEPLOY_CAVES }}" = "true" ]; then
            echo "deploy_caves=true" >> "$GITHUB_OUTPUT"
          else
            echo "deploy_caves=false" >> "$GITHUB_OUTPUT"
          fi

  deploy-overworld:
    runs-on: ubuntu-latest
    needs: check-deploy-caves

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          buildkitd-flags: --debug

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push Overworld Docker image to ECR
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile.overworld
          push: true
          tags: |
            ${{ steps.login-ecr.outputs.registry }}/dst-overworld:latest
            ${{ steps.login-ecr.outputs.registry }}/dst-overworld:${{ github.sha }}
          cache-from: type=inline
          cache-to: type=inline,mode=max

      - name: Deploy Overworld to App Runner
        uses: awslabs/amazon-app-runner-deploy@main
        with:
          service: DSTOverworld
          image: ${{ steps.login-ecr.outputs.registry }}/dst-overworld:latest
          port: 10999
          access-role-arn: ${{ secrets.AWS_ROLE_ARN }}
          region: ${{ secrets.AWS_REGION }}
          cpu: 1
          memory: 2
          copy-secret-env-vars: DST_SERVER_PASSWORD
          instance-role-arn: ${{ secrets.INSTANCE_ROLE_ARN }}

  deploy-caves:
    runs-on: ubuntu-latest
    needs: check-deploy-caves
    if: needs.check-deploy-caves.outputs.should_deploy == 'true'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          buildkitd-flags: --debug

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push Caves Docker image to ECR
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile.caves
          push: true
          tags: |
            ${{ steps.login-ecr.outputs.registry }}/dst-caves:latest
            ${{ steps.login-ecr.outputs.registry }}/dst-caves:${{ github.sha }}
          cache-from: type=inline
          cache-to: type=inline,mode=max

      - name: Deploy Caves to App Runner
        uses: awslabs/amazon-app-runner-deploy@main
        with:
          service: DSTCaves
          image: ${{ steps.login-ecr.outputs.registry }}/dst-caves:latest
          port: 11000
          access-role-arn: ${{ secrets.AWS_ACCESS_ROLE_ARN }}
          region: ${{ secrets.AWS_REGION }}
          cpu: 1
          memory: 2
          copy-secret-env-vars: DST_SERVER_PASSWORD
          instance-role-arn: ${{ secrets.INSTANCE_ROLE_ARN }}
