name: Deploy DST Server

on:
  push:
    branches:
      - main

permissions:
  id-token: write  # Required for GitHub OIDC
  contents: read   # Required for actions/checkout

jobs:
  deploy-dst-server:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push DST Server Docker image to ECR
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ steps.login-ecr.outputs.registry }}/dst-server:latest
            ${{ steps.login-ecr.outputs.registry }}/dst-server:${{ github.sha }}
          cache-from: type=inline
          cache-to: type=inline,mode=max

      - name: Deploy DST Server to App Runner
        uses: awslabs/amazon-app-runner-deploy@main
        with:
          service: DSTServer
          image: ${{ steps.login-ecr.outputs.registry }}/dst-server:latest
          port: 10999
          access-role-arn: ${{ secrets.AWS_ROLE_ARN }}
          region: ${{ secrets.AWS_REGION }}
          cpu: 1
          memory: 2
          copy-secret-env-vars: DST_SERVER_PASSWORD
          instance-role-arn: ${{ secrets.INSTANCE_ROLE_ARN }}
